{
 "title": "Mantis Node - App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "app_consensus_blocks_generate_timer_seconds_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_consensus_blocks_generate_timer_seconds_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_consensus_blocks_generate_timer_seconds_max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_consensus_blocks_generate_timer_seconds_max",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_consensus_blocks_generate_timer_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_consensus_blocks_generate_timer_seconds_sum",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_consensus_minedblocks_evaluation_timer_seconds_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_consensus_minedblocks_evaluation_timer_seconds_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_consensus_minedblocks_evaluation_timer_seconds_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_consensus_minedblocks_evaluation_timer_seconds_max",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_consensus_minedblocks_evaluation_timer_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_consensus_minedblocks_evaluation_timer_seconds_sum",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_json_rpc_healthcheck_error_counter_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_json_rpc_healthcheck_error_counter_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_json_rpc_methods_error_counter_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_json_rpc_methods_error_counter_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_json_rpc_methods_exception_counter_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_json_rpc_methods_exception_counter_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_json_rpc_methods_success_counter_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_json_rpc_methods_success_counter_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_json_rpc_methods_timer_seconds_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_json_rpc_methods_timer_seconds_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_json_rpc_methods_timer_seconds_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_json_rpc_methods_timer_seconds_max",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_json_rpc_methods_timer_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_json_rpc_methods_timer_seconds_sum",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_json_rpc_notfound_calls_counter_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_json_rpc_notfound_calls_counter_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_network_discovery_foundPeers_gauge﻿﻿",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_discovery_foundPeers_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_network_messages_received_counter_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_messages_received_counter_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_network_messages_sent_counter_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_messages_sent_counter_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_network_peers_blacklisted_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_blacklisted_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_network_peers_incoming_handshaked_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_incoming_handshaked_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_network_peers_outgoing_handshaked_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_outgoing_handshaked_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_network_peers_pending_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_pending_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Panel app_regularsync_blocks_propagation_timer_seconds_countTitle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_regularsync_blocks_propagation_timer_seconds_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Panel Titapp_regularsync_blocks_propagation_timer_seconds_maxle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_regularsync_blocks_propagation_timer_seconds_max",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_regularsync_blocks_propagation_timer_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_regularsync_blocks_propagation_timer_seconds_sum",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_sync_block_checkpoint_number_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_checkpoint_number_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_sync_block_difficulty_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_difficulty_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_sync_block_gasLimit_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_sync_block_gasLimit_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "app_sync_block_gasUsed_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_sync_block_gasUsed_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "app_sync_block_number_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_sync_block_number_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "app_sync_block_timeBetweenParent_seconds_gauge  ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_timeBetweenParent_seconds_gauge  ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_sync_block_transactions_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  app_sync_block_transactions_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app_sync_block_uncles_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_sync_block_uncles_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "app_transactions_pool_size_gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_transactions_pool_size_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}