{
 "title": "Mantis Node - JVM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "jvm_buffer_pool_capacity_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_buffer_pool_capacity_bytes" }
   ]
  },
  {
   "title": "jvm_buffer_pool_used_buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_buffer_pool_used_buffers" }
   ]
  },
  {
   "title": "jvm_buffer_pool_used_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_buffer_pool_used_bytes" }
   ]
  },
  {
   "title": "jvm_classes_loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_classes_loaded" }
   ]
  },
  {
   "title": "jvm_classes_loaded_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_classes_loaded_total" }
   ]
  },
  {
   "title": "jvm_classes_unloaded_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_classes_unloaded_total" }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_gc_collection_seconds_sum", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_info" }
   ]
  },
  {
   "title": "jvm_memory_bytes_committed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_committed" }
   ]
  },
  {
   "title": "jvm_memory_bytes_init",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_init" }
   ]
  },
  {
   "title": "jvm_memory_bytes_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_max" }
   ]
  },
  {
   "title": "jvm_memory_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_used" }
   ]
  },
  {
   "title": "jvm_memory_pool_allocated_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_allocated_bytes_total"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_committed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_init",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_pool_bytes_init" }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_pool_bytes_max" }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_pool_bytes_used" }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current" }
   ]
  },
  {
   "title": "jvm_threads_daemon",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_daemon" }
   ]
  },
  {
   "title": "jvm_threads_deadlocked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_deadlocked" }
   ]
  },
  {
   "title": "jvm_threads_deadlocked_monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_deadlocked_monitor" }
   ]
  },
  {
   "title": "jvm_threads_peak",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_peak" }
   ]
  },
  {
   "title": "jvm_threads_started_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_started_total" }
   ]
  },
  {
   "title": "jvm_threads_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_state" }
   ]
  }
 ]
}