{
 "title": "Morpho Node",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "morpho_block_number",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "  morpho_block_number", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "morpho_block_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "morpho_block_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "morpho_checkpoint_nb_peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "morpho_checkpoint_nb_peers", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "morpho_checkpoint_nb_votes_latest",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "morpho_checkpoint_nb_votes_latest",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "morpho_checkpoint_pushed_pow_block_number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  morpho_checkpoint_pushed_pow_block_number",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "morpho_checkpoint_stable_state_pow_block_number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "morpho_checkpoint_stable_state_pow_block_number",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "morpho_checkpoint_unstable_state_pow_block_number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "morpho_checkpoint_unstable_state_pow_block_number",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "morpho_latest_pow_block_number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "morpho_latest_pow_block_number", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "morpho_live_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "morpho_live_bytes", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}