FROM morpho-base:local

ADD morpho-configuration.yaml /root/.morpho/morpho-configuration.yaml
ADD private.key /root/.morpho/private.key
ADD public.key /root/.morpho/public.key
RUN mkdir -p /root/.morpho/db/db
