env:
  BUILDKITE_CLEAN_CHECKOUT: "false"
  OVERRIDE_BUILDKITE_REPO: "git@github.com:input-output-hk/mantis-automation.git"
  OVERRIDE_BUILDKITE_PIPELINE_SLUG: "mantis-automation"
  OVERRIDE_BUILDKITE_BRANCH: "ETCM-926-erc20-pr"

steps:
  - label: "Setup mantis"
    command:
      -  "pullrequest/setup_pottery_for_commit.sh"
    agents:
      - "host=e2e.mantis.ws"
    concurrency: 1
    concurrency_group: 'erc20-pr'
    env:
      BUILDKITE_CLEAN_CHECKOUT: "true"

  - label: "Setup tests"
    command: 
      -  "pullrequest/setup_tests.sh"
    plugins:
      - 'uber-workflow/run-without-clone'
    env:
      BUILDKITE_CLEAN_CHECKOUT: "false"
    agents:
      - "host=e2e.mantis.ws"
    concurrency: 1
    concurrency_group: 'erc20-pr'
 
  - label: "ERC20"
    command: 
      -  "pullrequest/run_tests.sh"
    plugins:
      - 'uber-workflow/run-without-clone'
    env:
      BUILDKITE_CLEAN_CHECKOUT: "false"
    agents:
      - "host=e2e.mantis.ws"
    concurrency: 1
    concurrency_group: 'erc20-pr'
    retry:
      automatic:
        - exit_status: 3
          limit: 10

  - wait: 
      continue_on_failure: true
  
  - label: "ERC20 report"
    command:
      -  "cd pullrequest/openzeppelin-contracts"
      -  "tar cvf mochawesome-report.tar mochawesome-report"
    plugins:
      - 'uber-workflow/run-without-clone'
    agents:
      -  "host=e2e.mantis.ws"
    artifact_paths: 
      -  "openzeppelin-contracts/mochawesome-report.tar"
    env:
      BUILDKITE_CLEAN_CHECKOUT: "false"
