env:
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  - label: "ERC20"
    #command: "git clone https://github.com/OpenZeppelin/openzeppelin-contracts.git"
    command: "git clone https://github.com/krzysztofpaliga-iohk/openzeppelin-contracts.git &&
    cd openzeppelin-contracts && 
		git checkout one_sc_test &&
		cd .. &&
    cp smartcontracts/openzeppelin/* openzeppelin-contracts/ &&
    cd openzeppelin-contracts &&
    . ~/.profile &&
    nvm use v14.17.0 &&
		npm install &&
    npm install mocha-junit-reporter &&
    npx hardhat --network sagano test test/token/ERC20/ERC20.test.js"
    agents:
    - "host=e2e.mantis.ws"
    plugins:
        - junit-annotate#v1.9.0:
            artifacts: openzeppelin-contracts/test-results.xml artifact_paths: "openzeppelin-contracts/test-results.xml"
