env:
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  - label: "ERC20"
    #command: "git clone https://github.com/OpenZeppelin/openzeppelin-contracts.git"
    command: "git clone https://github.com/krzysztofpaliga-iohk/openzeppelin-contracts.git"
    command: "cd openzeppelin-contracts && git checkout one_sc_test"
    command: "cp smartcontracts/openzeppelin/* openzeppelin-contracts/"
    command: "cd openzeppelin-contracts"
    command: ". ~/.profile"
    command: "nvm use v14.17.0 &&\nnpm install"
    command: "nvm install mocha-junit-reporter"
    command: "npx hardhat --network sagano test test/token/ERC20/ERC20.test.js"
    agents:
    - "host=e2e.mantis.ws"
