env:
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
    #command: "git clone https://github.com/OpenZeppelin/openzeppelin-contracts.git"
  - command: 'git clone https://github.com/krzysztofpaliga-iohk/openzeppelin-contracts.git &&
    cd openzeppelin-contracts && 
		git checkout one_sc_test &&
		cd .. &&
    cp smartcontracts/openzeppelin/* openzeppelin-contracts/ &&
    cd openzeppelin-contracts &&
    . ~/.profile &&
    nvm use v14.17.0 &&
		npm install &&
    npm install mocha-junit-reporter &&
    npx hardhat --network sagano test test/token/ERC20/ERC20.test.js &&
    wait $! &&
    junit2html test-results.xml test-results.html &&
    cat test-results.xml | buildkite-agent annotate --style "success" --context "junit"'
    artifact_paths: "openzeppelin-contracts/test-results.html"
    agents:
    - "host=e2e.mantis.ws"
