env:
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  - command: 'git clone https://github.com/OpenZeppelin/openzeppelin-contracts.git &&
    cp smartcontracts/openzeppelin/* openzeppelin-contracts/ &&
    cd openzeppelin-contracts &&
    . ~/.profile &&
    nvm use v14.17.0 &&
		npm install &&
    npm install mochawesome &&
    npx hardhat --network sagano test test/token/ERC20/ERC20.test.js &&'
    artifact_paths: "openzeppelin-contracts/mochawesome-report/mochawesome.html"
    agents:
    - "host=e2e.mantis.ws"
