env:
  BUILDKITE_CLEAN_CHECKOUT: "false"

steps:
  - label: "Setup tests"
    command: 
      -  "pullrequest/setup_tests.sh"
    env:
      BUILDKITE_CLEAN_CHECKOUT: "true"
    agents:
      - "host=e2e.mantis.ws"
 
  - wait: 
      continue_on_failure: true
  
  - label: "ERC20"
    command: 
      -  "pullrequest/run_tests.sh"
    plugins:
      - 'uber-workflow/run-without-clone'
    env:
      BUILDKITE_CLEAN_CHECKOUT: "false"
    agents:
      - "host=e2e.mantis.ws"
    retry:
      automatic:
        - exit_status: 3
          limit: 10

  - wait: 
      continue_on_failure: true
  
  - label: "ERC20 report"
    command:
      -  "cd pullrequest/openzeppelin-contracts"
      -  "tar cvf mochawesome-report.tar mochawesome-report"
    plugins:
      - 'uber-workflow/run-without-clone'
    agents:
      -  "host=e2e.mantis.ws"
    artifact_paths: 
      -  "openzeppelin-contracts/mochawesome-report.tar"
    env:
      BUILDKITE_CLEAN_CHECKOUT: "false"
