#!/bin/bash
if [ -f pullrequest/cleanup ] || ([ -f pullrequest/mantis ] && [ $BUILDKITE_RETRY_COUNT -eq 3 ])
then
	sudo rm -rf nomad/persistance/bootstrap-?/dot.mantis/pottery/rocksdb
	sudo rm -rf nomad/persistance/bootstrap-?/dot.mantis/pottery/logs
	ps aux | grep pottery-pr | head -n 1 | awk '{print $2}' | xargs sudo kill
fi
if [ -f kevm/cleanup ] || ([ -f kevm/openzeppelin-contracts ] && [ $BUILDKITE_RETRY_COUNT -eq 3 ])
then
	ps aux | grep pottery-kevm | head -n 1 | awk '{print $2}' | xargs sudo kill
fi
exit 0

