#!/bin/bash
export MANTIS_DIR=~/Develop/mantis/mantis-dist/
export HIVE_BOOTNODE="enode:abcd@bla:34"
export HIVE_LOGLEVEL=3
export HIVE_MINER="0x323542af434"
export HIVE_NETWORK_ID=8
export HIVE_CHAIN_ID=12
export HIVE_FORK_HOMESTEAD=0
export HIVE_FORK_DAO_BLOCK=1
export HIVE_FORK_TANGERINE=2
export HIVE_FORK_SPURIOUS=3
export HIVE_FORK_BYZANTIUM=4
export HIVE_FORK_CONSTANTINOPLE=5
export HIVE_FORK_PETERSBURG=6
export HIVE_FORK_ISTANBUL=7
export HIVE_FORK_MUIRGLACIER=8
export HIVE_FORK_BERLIN=9 
