test:
  name: hello
  workers:
    type: local
    number: 1
  rounds:
    - label: query
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 0.01
      workload:
        module: ../hello/query.js
#    - label: update
#      txNumber: 1000
#      rateControl:
#        type: fixed-rate
#        opts:
#          tps: 1
#      workload:
#        module: ../smartcontract/hello/update.js
